return {
	s("p", { t({ "```{python}", "" }), i(1), t({ "", "```", "", "" }) }),
	s("r", { t({ "```{r}", "" }), i(1), t({ "", "```", "", "" }) }),
	s("rs", {
		t({ "```{r}", "#| echo: true", "#| fig-width: 10", "#| fig-height: 4.5", "" }),
		i(1),
		t({ "", "```", "", "" }),
	}),
	s("j", { t({ "```{julia}", "" }), i(1), t({ "", "```", "", "" }) }),
	s("jh", {
		t({ "---", "title: '" }),
		i(1, "title"),
		t("'"),
		t({ "", "date: " }),
		t(os.date("%Y-%m-%d")),
		t({ "", "author: Robin Ender", "engine: julia", "---", "", "" }),
	}),
	s("rh", {
		t({ "---", "title: '" }),
		i(1, "title"),
		t("'"),
		t({ "", "date: " }),
		t(os.date("%Y-%m-%d")),
		t({ "", "author: Robin Ender", "---", "", "" }),
	}),
	s("rhp", {
		t({ "---", "title: '" }),
		i(1, "title"),
		t("'"),
		t({ "", "date: " }),
		t(os.date("%Y-%m-%d")),
		t({
			"",
			"author: Robin Ender",
			"format:",
			"  revealjs:",
			"    slide-number: true",
			"    incremental: true",
			"    theme: dark",
			"---",
			"",
			"",
		}),
	}),
	s("ph", {
		t({ "---", "title: '" }),
		i(1, "title"),
		t("'"),
		t({ "", "date: " }),
		t(os.date("%Y-%m-%d")),
		t({ "", "author: Robin Ender", "jupyter: python3", "---", "", "" }),
	}),
	s("php", {
		t({ "---", "title: '" }),
		i(1, "title"),
		t("'"),
		t({ "", "date: " }),
		t(os.date("%Y-%m-%d")),
		t({
			"",
			"author: Robin Ender",
			"jupyter: python3",
			"format:",
			"  revealjs:",
			"    slide-number: true",
			"    incremental: true",
			"    theme: dark",
			"---",
			"",
			"",
		}),
	}),
	s("f", { t({ "::: footer", "" }), i(1), t({ "", ":::", "", "" }) }),
	s("c", {
		t({ "::: columns", "", "::: {.column width='50%'}", "" }),
		i(1),
		t({ "", ":::", "::: {.column width='50%'}", "" }),
		i(2),
		t({ "", ":::", ":::", "", "" }),
	}),
	s("l", { t({ "^[<a href='" }), i(1), t({ "'>" }), i(2), t({ "</a>]" }) }),
}, {}
