return {
	s("t", {
		t({ "#figure(", "  table(", "    columns: " }),
		i(1),
		t({ "", "  ),", "  caption: [" }),
		i(2),
		t({ "]", ") <tbl_" }),
		i(3),
		t({ ">" }),
	}),
	s("i", {
		t({ "#figure(", '  image("' }),
		i(1),
		t({ '", width: 100%),', "  caption: [" }),
		i(2),
		t({ "]", ") <img_" }),
		i(3),
		t({ ">" }),
	}),
	s("g", {
		t({ "#subpar.grid(", '  figure(image("' }),
		i(1),
		t({ '"),', "caption: [" }),
		i(2),
		t({ "]), <img_" }),
		i(3),
		t({ ">,", '  figure(image("' }),
		i(4),
		t({ '"),', "caption: [" }),
		i(5),
		t({ "]), <img_" }),
		i(6),
		t({ ">,", "columns: (1fr, 1fr),", "caption: [" }),
		i(7),
		t({ "],", "  label: <img_" }),
		i(8),
		t({ ">", ")" }),
	}),
}
